name             'kitchen'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures kitchen'
long_description 'Installs/Configures kitchen'
version          '0.5.1'
depends          'virtualbox'
depends          'vagrant'

